name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error:
      ${{ contains(fromJson('["snapshot"]'), matrix.emacs_version) }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

        emacs_version:
          - '26.1'
          - '26.2'
          - '26.3'
          - '27.1'
          - '27.2'
          - '28.1'
          - 'snapshot'

    steps:
      - uses: actions/checkout@v3
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: conao3/setup-keg@master

      - run: keg install
      - run: keg run test-all
        env:
          UNDERCOVER_FORCE: true
      - uses: codecov/codecov-action@v2

  lint:
    runs-on: ubuntu-latest
    continue-on-error: ${{ true }}
    steps:
      - uses: actions/checkout@v1
      - uses: purcell/setup-emacs@master
        with:
          version: '28.1'
      - uses: conao3/setup-keg@master
      - run: keg lint
